# -*- coding: utf-8 -*-
"""Sales Summary Using SQL in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsJ1OpkokvBojk08jow57YacfdilwWVj
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# 1) Create / connect to the database file
conn = sqlite3.connect("sales_data.db")   # creates file in current folder
cursor = conn.cursor()

# 2) Create table (if not exists)
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
);
""")

# 3) Clear old data (safe while developing)
cursor.execute("DELETE FROM sales")
conn.commit()

# 4) Insert medium sample data
sample_data = [
    ("Laptop", 5, 55000),
    ("Laptop", 3, 54000),
    ("Mouse", 20, 500),
    ("Mouse", 15, 450),
    ("Keyboard", 10, 1200),
    ("Keyboard", 12, 1100),
    ("Monitor", 4, 8000),
    ("Monitor", 6, 8200)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)
conn.commit()

# 5) Run SQL query to get totals
query = """
SELECT product,
       SUM(quantity) AS total_qty,
       SUM(quantity * price) AS revenue
FROM sales
GROUP BY product;
"""
df = pd.read_sql_query(query, conn)

# 6) Print results (simple)
print("\n=== SALES SUMMARY ===\n")
print(df.to_string(index=False))

# 7) Plot bar chart (revenue by product)
plt.figure(figsize=(8,5))
plt.bar(df['product'], df['revenue'])
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.title("Revenue by Product")
plt.tight_layout()
plt.savefig("sales_chart.png")   # saves chart file
plt.show()

# 8) Close connection
conn.close()



